server:
  port: 9000
  servlet:
    context-path: /springclound
spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server2:8672/eureka,http://eureka-server3:8673/eureka
  instance:
    hostname: localhost
