server:
  port: 9000
  servlet:
    context-path: /springclound
spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8672/eureka
  instance:
    hostname: localhost
